# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9e496eafe4208b50a6fbff62b418afc0c6566048966bc337d7dfc9db895a95e00a71d7aacd2764434ffae3a0dc149859cb419e91d4b693bbd66a5afa2d8b453

test:
  secret_key_base: 4abd9cc2d31cb297abaec171fb3e42e3ba6cd3ead8edf28078d1c906d1017d30a8efe2faa72cc39ab3f0053f217a33407ea9769fe98121a95ed6a453842b58d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
